#!/bin/bash

blesh_path=~/.local/share/blesh/ble-0.4.0-devel3/ble.sh
if [[ -r $blesh_path && $- == *i* ]]; then
    source "$blesh_path" --attach=none
fi

PATH=~/.local/bin:$PATH
PATH="${PATH}:${HOME}/.krew/bin"

alias dotfiles=chezmoi

# Don't do anything of we don't have mise installed
if type -t mise >> /dev/null; then
    eval "$(mise activate bash)"
    # Enable other scripts that follow to use stuff that mise provides
    eval "$(mise hook-env -s bash)"
fi

if [[ -r /etc/profile.d/bash_completion.sh ]]; then
    source /etc/profile.d/bash_completion.sh
fi

if type -t starship >> /dev/null; then
    eval "$(starship init bash)"
fi

[[ ${BLE_VERSION-} ]] && ble-attach

if type -t carapace >> /dev/null; then
    export CARAPACE_BRIDGES='cobra,bash'
    source <(carapace _carapace)
fi

if type -t atuin >> /dev/null; then
    eval "$(atuin init bash)"
fi
