[tools]
usage = "1.7.2"
yq = "4.43.1"
github-cli = "2.49.0"
pipx = "1.5.0"
python = "3.11.9"
src = "0.1.0"

[plugins]
src = "https://github.com/ifireball/asdf-src.git"

[settings]
experimental = true
