[tools]
usage = "2.2.2"
yq = "4.43.1"
github-cli = "2.49.0"
pipx = "1.5.0"
python = "3.11.9"
src = "0.1.0"
"ubi:starship/starship" = "1.23.0"
"ubi:carapace-sh/carapace-bin" = { version = "1.3.2", exe = "carapace" }
"ubi:atuinsh/atuin" = { version = "18.6.1", matching = ".tar.gz" }
zoxide = "0.9.8"
fzf = "0.62.0"
cosign = "2.5.2"
gitsign = "0.13.0"
ghq = "1.8.0"

[alias]
src = "https://github.com/ifireball/asdf-src.git"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["python"]
